DroidSansArabic.ttf usr/share/fonts/truetype/droid/
DroidSans-Bold.ttf usr/share/fonts/truetype/droid/
DroidSansHebrew.ttf usr/share/fonts/truetype/droid/
DroidSansJapanese.ttf usr/share/fonts/truetype/droid/
DroidSansThai.ttf usr/share/fonts/truetype/droid/
DroidSansMono.ttf usr/share/fonts/truetype/droid/
DroidSans.ttf usr/share/fonts/truetype/droid/
DroidSerif*.ttf usr/share/fonts/truetype/droid/
